### ISSUE TITLE
Alias error after create the project

### ISSUE THREAD

**Issue by 3lackd-projetos** [bknd-io/bknd#210]
I got this error just after create the project

`npx bknd create -i react-router`

then after a npm run dev, or pnpm run dev or bun run dev (i've tryed create with pnpm and bun too after the first error to check if repeats)

_Cannot find module '~/bknd' imported from 'C:/Users/Tobias/Work/my-portfolio-dynamic/app/routes/admin.$.tsx'_

Maybe a possible bug configuration for windows? I'm running windows 10 and couldn't test in other enviroments to check if it's a windows thing.

This error happens with npm, pnpm and bun

`$ node -v
v22.16.0`

`$ npm -v
10.9.2`

`$ pnpm -v
10.12.4`

**Comment by dswbx** [comment]
hey @3lackd-projetos this issue sounds strange, it works fine on my Mac, and on my Windows 11 ARM virtual machine (with Node.js 22.17.1, but I don't think that this makes a difference). 

The file should exist, at least from the template. You may 
* try to remove the path aliases (e.g. on `app/routes/admin.$.tsx` import from `"../bknd"` instead of `"~/bknd"`
* try updating to node 22.17.1 
* verify that react router works by running a fresh RR project (using path aliases)
* try to force add the alias in vite, maybe there is an edge case

To force add the alias in vite, you could adjust the `vite.config.ts` as follows:

```diff
import { reactRouter } from "@react-router/dev/vite";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
+import { resolve } from "node:path";

export default defineConfig({
   plugins: [tailwindcss(), reactRouter(), tsconfigPaths()],
+   resolve: {
+      alias: {
+         "~": resolve(__dirname, "app"),
+      },
   },
});
```

Hope this helps!

**Comment by eutobias** [comment]
Works like a charm after update to 22.17.1, by the way i posted with wrong account up there!

Thank you
